// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7mTPG14LVIy-rfxHToxSNiHzErC_7WMs',
    appId: '1:228051656340:web:2856a53d552cff85991e81',
    messagingSenderId: '228051656340',
    projectId: 'nexedhub',
    authDomain: 'nexedhub.firebaseapp.com',
    storageBucket: 'nexedhub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9TUXOM-J4lrd3biHMdtjumo-8RxCcb4',
    appId: '1:228051656340:android:0009d12460bd3abf991e81',
    messagingSenderId: '228051656340',
    projectId: 'nexedhub',
    storageBucket: 'nexedhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPz2gdg13as_TkSOV-YzQXLfmnLe2HaZo',
    appId: '1:228051656340:ios:45158c23ab10b199991e81',
    messagingSenderId: '228051656340',
    projectId: 'nexedhub',
    storageBucket: 'nexedhub.appspot.com',
    iosBundleId: 'com.example.nexedhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPz2gdg13as_TkSOV-YzQXLfmnLe2HaZo',
    appId: '1:228051656340:ios:7b9fb132f13c1efd991e81',
    messagingSenderId: '228051656340',
    projectId: 'nexedhub',
    storageBucket: 'nexedhub.appspot.com',
    iosBundleId: 'com.example.nexedhub.RunnerTests',
  );
}
